### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by Matthieu05** [iiFlamiinBlaze/OtherPlugins#1]
The command for set durability works but when I break blocks or kill watches, the item is not used.
![screenshot_2018-05-20-18-25-38](https://user-images.githubusercontent.com/17796405/40280980-81cc8c1a-5c5b-11e8-86fd-65fb9099c4d8.png)
![screenshot_2018-05-20-18-25-00](https://user-images.githubusercontent.com/17796405/40280983-8cef5ab4-5c5b-11e8-82f2-0a1d93fb9114.png)

**Comment by iiFlamiinBlaze** [comment]
Bones do not have durability... try it on a sword.
